import bpy
import os


from ..utils.errors.exceptions import RigCollectionNotFound, DrivingPathnNotFound, WrongContext
from ..ui.utils import show_message_box
from ..logger import log_error, log_info

from ..utils.resources import get_resource_path, upload_asset, get_addon_path
from ..utils.functions import obVisLoc, obVisRot, obVisSca, get_active_curve_length, get_collection_by_name
from ..utils.validations import validate_lc_object
from ..globals import *

class OBJECT_OT_prepare_animation(bpy.types.Operator):
    bl_label = "Animate Vehicle!"
    bl_idname = "object.prepare_animation"
    bl_description = "Floor the Throttle and Drop the Brake!"

    def _set_physics(self, scene, new_animation):
        values = ANIMATIONS.get(new_animation, ANIMATIONS_DEFAULT_VALUES)
        props = scene.lc.find_selected().properties

        # Gravity | End Frame
        (
            props.use_gravity,
            scene.frame_end,
        ) = values

        scene.frame_start = 25

    def _clear_handle_transforms(self, car_bones):
        # Set a few values to 0 - if animated it will be overridden automatically
        car_bones[B_SWITCH_AIRBOURNE].location[1] = 0
        car_bones[B_SWITCH_AIRBOURNE_ROT].location[1] = 0
        car_bones[B_BODY_DRIFT].rotation_euler[1] = 0
        car_bones[B_SLIDER_PIVOT_POS].location[1] = 0

        # Animation handles
        car_bones[B_CUSTOM_MASS].location = (0, 0, 0)
        car_bones[B_INTERACTIVE_WHEEL_PAIR].location[0] = 0
        car_bones[B_WHEEL_CUSTOM_TURN_FR].rotation_euler[2] = 0
        car_bones[B_WHEEL_CUSTOM_TURN_FL].rotation_euler[2] = 0
        car_bones[B_WHEEL_CUSTOM_TURN_RR].rotation_euler[2] = 0
        car_bones[B_WHEEL_CUSTOM_TURN_RL].rotation_euler[2] = 0
        car_bones[B_WHEEL_CUSTOM_SPIN_FR].rotation_euler[0] = 0
        car_bones[B_WHEEL_CUSTOM_SPIN_FL].rotation_euler[0] = 0
        car_bones[B_WHEEL_CUSTOM_SPIN_RR].rotation_euler[0] = 0
        car_bones[B_WHEEL_CUSTOM_SPIN_RL].rotation_euler[0] = 0
        car_bones[B_WHEEL_CUSTOM_SUSPENSION_FR].location[1] = 0
        car_bones[B_WHEEL_CUSTOM_SUSPENSION_FL].location[1] = 0
        car_bones[B_WHEEL_CUSTOM_SUSPENSION_RR].location[1] = 0
        car_bones[B_WHEEL_CUSTOM_SUSPENSION_RL].location[1] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_FR].rotation_euler[1] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_FL].rotation_euler[1] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_RR].rotation_euler[1] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_RL].rotation_euler[1] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_FR].rotation_euler[2] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_FL].rotation_euler[2] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_RR].rotation_euler[2] = 0
        car_bones[B_WHEEL_CAMBEROFFSET_RL].rotation_euler[2] = 0
        car_bones[B_WHEEL_ARCH_LIMIT_FR].location[1] = 0
        car_bones[B_WHEEL_ARCH_LIMIT_FL].location[1] = 0
        car_bones[B_WHEEL_ARCH_LIMIT_RR].location[1] = 0
        car_bones[B_WHEEL_ARCH_LIMIT_RL].location[1] = 0
        car_bones[B_BODY_DRIFT_OFFSET].location[0] = 0
        
    def _import_data_path(self, file_path, driving_path, new_animation):
        try:
            upload_asset(file_path, "Curve", new_animation)

            if driving_path:  # this way or without the +
                new_animation_curve = bpy.context.selected_objects[0].data
                bpy.ops.object.delete()  # Delete the appended object, but keeping the curve data
                driving_path.data = new_animation_curve
            else:
                # Otherwise, import it and don't delete anything
                bpy.context.selected_objects[0].name = driving_path.name
                bpy.ops.object.location_clear(clear_delta=False)
        except:
            log_error("Curve asset does not exist.", "prepare_animation")

    def _import_action_data(self, file_path, rig_object, new_animation):
        try:
            upload_asset(file_path, "Action", new_animation)
            new_animation_data = bpy.data.actions[new_animation]
            rig_object.animation_data.action = new_animation_data

        except:
            log_error("Action asset does not exist.", "OBJECT_OT_prepare_animation")

    def _import_ground_detect_data(
        self, file_path, scene_objects, new_animation, driving_path
    ):
        scene = bpy.context.scene
        collection_name = scene.car_collection.name

        try:
            for obj in scene_objects:  # Check if any old col objects exists which was generated by this particular car
                if "col_" in obj.name and collection_name in obj.name:
                    bpy.data.objects.remove(obj, do_unlink=True)
            
            lower_new_animation = new_animation.lower()
            lower_new_animation = lower_new_animation.replace(" ", "_")

            upload_asset(file_path, "Object", "col_" + lower_new_animation)
            new_col_data = bpy.context.selected_objects[0]

            for collection in new_col_data.users_collection:
                collection.objects.unlink(new_col_data)

            bpy.data.collections["GroundDetection"].objects.link(new_col_data)

            # move + rot collider to driving path
            new_col_data.location = driving_path.location
            new_col_data.rotation_euler[2] = driving_path.rotation_euler[2]

            new_col_data.name += ("_" + collection_name)

        except:
            log_error("Unabe to find collection GroundDetection.", "prepare_animation")

    def execute(self, context):
        scene = context.scene
        active_car = scene.lc.find_selected()

        # Make sure something is selected and we are in object mode
        try:
            bpy.ops.object.mode_set(mode="OBJECT")
        except:
            log_error(
                "Unable to find selected object or set object mode",
                "prepare_animation",
            )

        # Create undo point
        bpy.ops.ed.undo_push()
        
        ui_custom_path = active_car.properties.custom_path
        ui_path_anim_intpl = active_car.properties.path_anim_intpl

        multi_edit = scene.settings.edit_all_mode
        cars = []
        
        if multi_edit: cars = scene.lc.cars
        else: cars.append(active_car)

        for active_car in cars:   
            rig_object = active_car.rig_object
            
            try: 
                driving_path = active_car.driving_path
            except RigCollectionNotFound as e: 
                e.show_error_message(title="Cannot Animate Vehicle")
                return {"CANCELLED"}
            
            if not validate_lc_object(active_car.driving_path):
                return {"CANCELLED"}

            if not validate_lc_object(rig_object):
                return {"CANCELLED"}
            
            props = active_car.properties
            addon_root = ".".join(__package__.split(".")[:-2])
            addon_preferences = context.preferences.addons[addon_root].preferences
            multi_edit = scene.settings.edit_all_mode

            if driving_path.name not in bpy.context.scene.objects:
                try: 
                    active_car.rig_collection.objects.link(driving_path)
                
                except RigCollectionNotFound as e: 
                    e.show_error_message(title="Cannot Animate Vehicle")
                    return {"CANCELLED"}

            # Make sure the car is riged (the rig_collection is there)
            try: 
                active_car.get_rig_collection()
            except DrivingPathnNotFound as e: 
                e.show_error_message(title="Cannot Animate Vehicle")
                return {"CANCELLED"}

            bpy.ops.object.select_all(action="DESELECT")

            rig_object.select_set(True)
            bpy.context.view_layer.objects.active = rig_object
            # Make sure Blender didn't switch to "POSE mode" since the armature is now active
            try:
                bpy.ops.object.mode_set(mode="OBJECT")
            except WrongContext as e: 
                e.show_error_message(title="Cannot Animate Vehicle")
                return {"CANCELLED"}

            active_car.path_changed = True


            if ui_custom_path is None: 
                new_animation = os.path.splitext(
                    bpy.data.window_managers["WinMan"].animation_presets
                )[0]

                # set physics settings
                self._set_physics(scene, new_animation)

                # set bones settings
                self._clear_handle_transforms(rig_object.pose.bones)

                # Setup file reference to addons folder
                file_path_default_assets = get_resource_path(FILENAME_BLEND)

                if file_path_default_assets is None:
                    text = "Could not access Add-on. Please re-install."
                    log_error(text, "OBJECT_OT_prepare_animation")
                    show_message_box(title="Unable to animate car", message=text, icon="ERROR")
                    return {"CANCELLED"}


                legacy_import = True
                if scene.settings.filter_anim_presets == 'custom' or scene.settings.filter_anim_presets == 'library':
                    legacy_import = False 


                if legacy_import:
                    # Import path data
                    self._import_data_path(file_path_default_assets, driving_path, new_animation)

                    # Import action data
                    self._import_action_data(file_path_default_assets, rig_object, new_animation)

                    # Import Ground detect data
                    self._import_ground_detect_data(
                        file_path_default_assets, scene.objects, new_animation, driving_path
                    )

                else:

                    ground_detect_collection = get_collection_by_name(COLLECTIONNAME_GROUNDDETECT, scene.collection)
                    
                    for obj in scene.objects:  # Check if any old col objects exists which was generated by this particular car
                        if "col_" in obj.name and ground_detect_collection in obj.users_collection:
                            bpy.data.objects.remove(obj, do_unlink=True)

                    addons_path = get_addon_path()
                    addon_root = ".".join(__package__.split(".")[:-2])
                    addon_preferences = bpy.context.preferences.addons[addon_root].preferences
                    
                    if scene.settings.filter_anim_presets == "custom":
                        file_dir = os.path.join(addons_path, "assets", "images", "custom_presets")

                    elif scene.settings.filter_anim_presets == "library":
                        file_dir = os.path.join(addon_preferences.anim_preset_lib_path)


                    sel_anim = os.path.splitext(bpy.data.window_managers["WinMan"].animation_presets)[0]

                    file_name = (sel_anim + ".blend")
                    file_path = os.path.join(file_dir, file_name)

                    try:
                        with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
                            for coll_name in data_from.collections:
                                data_to.collections.append(coll_name)

                            for obj_name in data_from.objects:
                                if FILENAME_DRIVINGPATH in obj_name:
                                    data_to.objects.append(obj_name)

                            for action_name in data_from.actions:
                                data_to.actions.append(action_name)


                        for coll in data_to.collections:
                            if coll is not None:
                                for obj in coll.objects:
                                    bpy.data.collections[COLLECTIONNAME_GROUNDDETECT].objects.link(obj)
                        
                        for obj in data_to.objects:
                            if obj is not None:
                                driving_path.data = obj.data
                                driving_path.location = obj.location
                                driving_path.rotation_euler = obj.rotation_euler
                                driving_path.scale = obj.scale
                        
                        for action in data_to.actions:
                            if action is not None:
                                rig_object.animation_data.action = action

                    except: 
                        show_message_box("Could not import Animation Preset. Please make sure the Preset file is intact", "Error in Preset", "ERROR")
                        log_error(f"Could not import Anim Preset", "OBJECT_OT_prepare_animation")
                        bpy.ops.object.select_all(action="DESELECT")
                        bpy.ops.ed.undo_push()
                        bpy.ops.ed.undo()
                        return {"CANCELLED"}


                # make sure animation starts right away on playback
                if scene.frame_start < 25 and  scene.settings.filter_anim_presets == 'default':
                    scene.frame_start = 25

            
            else:
                active = ui_custom_path
                path_scale = active.scale[0]
                ob = driving_path

                # Check if Driving Path is accessible
                ob.select_set(True)
                if not ob.select_get():
                    show_message_box(
                    f"Launch Control Driving Path not found in scene. Please make sure it's not hidden or deleted.",
                    "Searching for Driving Path",
                    "ERROR",
                    )
                    log_error("Could not select Driving Path", "OBJECT_OT_prepare_animation")
                    return {"CANCELLED"}
                
                # check for multiple splines
                if len(active.data.splines) > 1:
                    show_message_box(
                    "Could not use the User Path. There seems to be multiple splines inside the path object. Please delete all but 1 spline in the User Path",
                    "Vehicle Animation",
                    "ERROR",
                    )
                    log_error("Multiple Splins in User Curve object", "OBJECT_OT_prepare_animation")
                    return {"CANCELLED"}

                obVisLoc(ob, active, context)
                obVisRot(ob, active, context)
                obVisSca(ob, active, context)

                ob.data = active.data.copy()

                ob.data.resolution_u = 128
                ob.data.bevel_depth = 0.06
                ob.data.use_path = True
                ob.modifiers["Shrinkwrap"].use_apply_on_spline = True

                bpy.ops.object.select_all(action="DESELECT")
                ob.select_set(True)
                bpy.context.view_layer.objects.active = ob

                bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
                bpy.ops.object.refresh_path_len()

                path_len = get_active_curve_length(driving_path)

                b_points = len(ob.data.splines[0].bezier_points)
                n_points = len(ob.data.splines[0].points)

                for point in ob.data.splines[0].bezier_points:
                    point.radius = 1
                
                for point in ob.data.splines[0].points:
                    point.radius = 1

                sum_points = b_points + n_points
                dist_between_points = path_len/sum_points
                ob.data.resolution_u = int(16*dist_between_points)

                if addon_preferences.override_anim_on_path_change:
                    self._clear_handle_transforms(rig_object.pose.bones)
                    new_animationData = bpy.data.actions.new("User_Path_Auto_Action")
                    rig_object.animation_data.action = new_animationData

                    speed_rotate_bone = rig_object.pose.bones["bone_Speed_Rotate"]
                    restore_offset = speed_rotate_bone.rotation_euler[2]

                    speed_rotate_bone.rotation_euler[2] = 0
                    speed_rotate_bone.keyframe_insert(data_path="rotation_euler", index=2, frame=props.frame_custom_path_start)

                    speed_rotate_bone.rotation_euler[2] = path_len/9.99
                    speed_rotate_bone.keyframe_insert(data_path="rotation_euler", index=2, frame=props.frame_custom_path_end)

                    speed_rotate_bone.rotation_euler[2] = restore_offset

                    for key in rig_object.animation_data.action.fcurves[0].keyframe_points:
                        key.handle_left_type = ui_path_anim_intpl
                        key.handle_right_type = ui_path_anim_intpl

                        if ui_path_anim_intpl == 'VECTOR':
                            key.interpolation = "LINEAR"
                
                props = active_car.properties
                props.custom_path = None

                # Remove user path
                
                driving_path_list = []

                for car in scene.lc.cars:
                    if car.driving_path:
                        driving_path_list.append(car.driving_path.name)


                if ui_custom_path.name not in driving_path_list:

                    for collection in ui_custom_path.users_collection:
                        collection.objects.unlink(ui_custom_path)

                    
                    objs = bpy.data.objects
                    if (not multi_edit) or (multi_edit and active_car == cars[len(cars)-1]):  # delete old path to not confused the user about which is being used, but ONLY delete it for the last car if multi-car is active
                        objs.remove(ui_custom_path, do_unlink=True)

                scene.frame_start = props.frame_custom_path_start
                scene.frame_end = props.frame_custom_path_end + 30

            

            ### WRAP UP AND IMPROVE UX ###

            # make sure active frame is set back to 0 for correct physics results
            scene.frame_current = 0
            


            # Reset physics cache and removed baked physics if exists
            physics_enabled = active_car.rig_object.pose.bones[B_SWITCH_USE_SIMULATION].location[1]

            if physics_enabled:
                baked_physics = active_car.properties.baked_physics

                if baked_physics:
                    bpy.ops.object.free_physics()
                
                else:
                    bpy.ops.object.refresh_physics()


            if addon_preferences.apply_path_color:
                white = [0.8,0.8,0.8,1]
                red = [0.745,0.114,0.105,1]
                orange = [0.863,0.361,0.089,1]
                yellow = [0.871,0.708,0.091,1]
                green = [0.195,0.597,0.195,1]
                blue = [0.109,0.462,0.815,1]
                purple = [0.262,0.100,0.694,1]
                pink = [0.558,0.168,0.474,1]
                brown = [0.191,0.089,0.053,1]
                

                match active_car.properties.color_tag:
                    case 'COLOR_01': 
                        color_rgb = red
                    
                    case 'COLOR_02': 
                        color_rgb = orange

                    case 'COLOR_03': 
                        color_rgb = yellow

                    case 'COLOR_04': 
                        color_rgb = green

                    case 'COLOR_05': 
                        color_rgb = blue

                    case 'COLOR_06': 
                        color_rgb = purple

                    case 'COLOR_07': 
                        color_rgb = pink

                    case 'COLOR_08': 
                        color_rgb = brown

                    case _:
                        color_rgb = white
                
                mat_name = (f"driving_path_{active_car.rig_collection.name}")
                mat = bpy.data.materials.get(mat_name)

                if mat is None:
                    mat = bpy.data.materials.new(name=mat_name)

                if driving_path.data.materials:
                    driving_path.data.materials[0] = mat
                else:
                    driving_path.data.materials.append(mat)

                driving_path.material_slots[0].material.diffuse_color = color_rgb
                driving_path.display_type = 'TEXTURED'

        ui_custom_path = None  
        #scene.use_preview_range = False       


        # Create undo point
        bpy.ops.ed.undo_push()
            
        return {"FINISHED"}

        
